version: '3.7'

services:
  mosquitto-server:
    build:
      context: .
    container_name: mosquitto-server
    restart: always
    ports: 
      - "10088:8080"
    logging:
      options:
        max-size: 1m
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/mnt/kubernetes/certbot:/certs"
      - "/mnt/kubernetes/nginx-reverse-proxy/conf:/etc/nginx"
      - "/mnt/kubernetes/docker-registry/auth:/auth"
      - "/mnt/kubernetes/nginx-reverse-proxy/var/www:/var/www"
