version: '3.7'

services:
  mosquitto-server:
    build:
      context: .
    container_name: mosquitto-server
    restart: always
    ports: 
      - "10088:1883"
    logging:
      options:
        max-size: 1m
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/mnt/kubernetes/certbot:/certs"
      - "/mnt/kubernetes/mosquitto/config:/mosquitto/config"
      - "/mnt/kubernetes/mosquitto/log:/mosquitto/log"
      - "/mnt/kubernetes/mosquitto/data:/mosquitto/data"
